const jokes = [
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why did the chicken join a band? Because it had the drumsticks!",
    "Why don't programmers like nature? It has too many bugs.",
    "How does a penguin build its house? Igloos it together!",
    "Why was the math book sad? Because it had too many problems.",
    "Why don't some couples go to the gym? Because some relationships don't work out.",
    "What do you call fake spaghetti? An impasta!",
    "Why don't skeletons fight each other? They don't have the guts.",
    "What did one ocean say to the other ocean? Nothing, they just waved.",
    "Why did the scarecrow win an award? Because he was outstanding in his field!",
    "Why don't oysters donate to charity? Because they are shellfish.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "What do you call a fish with no eyes? Fsh.",
    "Why did the golfer bring two pairs of pants? In case he got a hole in one.",
    "Why don't some fish play piano? Because you can't tuna fish.",
    "Why did the bicycle fall over? It was two-tired.",
    "What do you call cheese that isn't yours? Nacho cheese.",
    "Why did the physics teacher break up with the biology teacher? There was no chemistry.",
    "Why don't vampires go to barbecues? They don't like steak.",
    "Why did the computer go to the doctor? Because it had a virus.",
    "Why don't you ever see elephants hiding in trees? Because they're so good at it.",
    "Why did the scarecrow become a successful neurosurgeon? He was outstanding in his field.",
    "Why don't some relationships work out? Because they have too many issues.",
    "Why was the broom late? It swept in.",
    "Why don't some people like stairs? Because they're always up to something.",
    "What do you get if you cross a snowman and a vampire? Frostbite.",
    "Why was the math book sad? Because it had too many problems.",
    "Why don't sharks eat clowns? Because they taste funny.",
    "Why did the golfer bring extra socks? In case he got a hole in one.",
    "Why don't ghosts use elevators? Because they lift their spirits.",
    "Why did the scientist install a knocker on his door? He wanted to win the No-bell prize.",
    "Why don't cows wear shoes? Because they lactose.",
    "Why did the banana go to the doctor? Because it wasn't peeling well.",
    "Why did the picture go to jail? Because it was framed.",
    "Why did the music teacher go to jail? Because she got caught with the notes.",
    "Why don't ants get sick? Because they have tiny ant-bodies.",
    "Why did the chicken go to the seance? To talk to the other side.",
    "Why did the invisible man turn down the job offer? He couldn't see himself doing it.",
    "Why don't you ever see skeletons fighting? They don't have the guts.",
    "Why don't eggs tell jokes? They might crack up.",
    "Why don't some restaurants have good service? Because they lack table manners.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "Why don't some people tell secrets? Because they can't keep their mouths shut.",
    "Why don't some actors break a leg? Because every play needs a cast.",
    "Why don't some clocks work? Because they don't have the time.",
    "Why don't some cars start? Because they have a dead battery.",
    "Why did the tree go to the barber? It needed a trim.",
    "Why don't some people like math? Because it's too complicated.",
    "Why don't some birds fly? Because they're afraid of heights.",
    "Why did the tomato turn red? Because it saw the salad dressing.",
    "Why don't some dogs bark? Because they're too quiet.",
    "Why did the cat sit on the computer? To keep an eye on the mouse.",
    "Why don't some cats like water? Because they don't want to get their fur wet.",
    "Why did the spider go on the computer? To check its web site.",
    "Why don't some bees fly? Because they're too busy buzzing.",
    "Why did the butterfly go to school? To learn about metamorphosis.",
    "Why don't some plants grow? Because they lack sunlight.",
    "Why did the cookie go to the doctor? Because it was feeling crummy.",
    "Why don't some flowers bloom? Because they lack water.",
    "Why did the bird go to the library? To check out a book.",
    "Why don't some fish swim? Because they're too tired.",
    "Why did the frog call his insurance company? He had a jump in his car.",
    "Why don't some animals sleep? Because they're nocturnal.",
    "Why did the cow go to space? To see the moooon.",
    "Why don't some insects bite? Because they're too friendly.",
    "Why did the lion go to the gym? To get in shape.",
    "Why don't some people swim? Because they're afraid of water.",
    "Why did the bear go to the dentist? To get its teeth checked.",
    "Why don't some people fly? Because they're afraid of heights.",
    "Why did the penguin go to the party? To break the ice.",
    "Why don't some people dance? Because they have two left feet.",
    "Why did the dolphin go to school? To learn how to play.",
    "Why don't some people laugh? Because they're too serious.",
    "Why did the rabbit go to the gym? To get in shape.",
    "Why don't some people smile? Because they're too sad.",
    "Why did the owl go to the library? To read a book.",
    "Why don't some people talk? Because they're too shy.",
    "Why did the kangaroo go to the party? To have a hopping good time.",
    "Why don't some people listen? Because they're too distracted.",
    "Why did the sheep go to the barber? To get a trim.",
    "Why don't some people work? Because they're too lazy.",
    "Why did the horse go to the doctor? Because it was feeling hoarse.",
    "Why don't some people run? Because they're too tired.",
    "Why did the elephant go to the gym? To get in shape.",
    "Why don't some people read? Because they're too busy.",
    "Why did the giraffe go to the party? To have a tall time.",
    "Why don't some people write? Because they're too lazy.",
    "Why did the pig go to the market? To buy some groceries.",
    "Why don't some people cook? Because they're too lazy.",
    "Why did the duck go to the party? To have a quacking good time.",
    "Why don't some people clean? Because they're too lazy.",
    "Why did the chicken go to the party? To have a clucking good time.",
    "Why don't some people exercise? Because they're too lazy.",
    "Why did the fish go to the market? To buy some groceries.",
    "Why don't some people shop? Because they're too lazy.",
    "Why did the cow go to the party? To have a mooooving time.",
    "Why don't some people travel? Because they're too lazy.",
    "Why did the goat go to the market? To buy some groceries.",
    "Why don't some people garden? Because they're too lazy.",
    "Why did the horse go to the party? To have a galloping good time."
];

function generateJoke() {
    const jokeElement = document.getElementById('joke');
    const randomIndex = Math.floor(Math.random() * jokes.length);
    jokeElement.textContent = jokes[randomIndex];
}

// Generate a joke on page load
generateJoke();
